name: Feature
description: A new feature or enhancement
title: "feat: "
labels: ["feature"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Details
      description: What needs to be built and why?
      value: |
        ## Problem
        -
        ## Acceptance Criteria (User Story)
        -
        ## Notes (optional)
        -
    validations:
      required: true
